### ISSUE TITLE
Cannot determine whether updateLocale is finished or not

### ISSUE THREAD

**Issue by hanmajid** [nylo-core/support#2]
Hi, I have a question. I am trying out Nylo and having a problem with the localization, specifically the `updateLocale` method. As you can see in the snippet below, the method doesn't return anything. When I was trying to switch between two locales, sometimes **the locale doesn't change**. I'm guessing this is because the `reloadLocale` hasn't finished updating the locale. Is it possible to make `updateLocale` **return a Future** of when the locale has been updated. Thanks in advance!

```dart
// File: support/lib/localization/app_localization.dart

/// A locale class used to manage the current locale state.
class AppLocale {

  /// Updates the current locale for the app.
  /// Provide the [locale] you wish to use like Locale("es")
  /// The locale needs to also exist within your /lang directory
  updateLocale(BuildContext context, Locale locale) {
    this.locale = locale;
    reloadLocale(context, locale);
  }
}
```

**Comment by agordn52** [comment]
Thanks, this is resolved in [v2.1.0](https://github.com/nylo-core/nylo/releases/tag/v2.1.0)
