### ISSUE TITLE
Text Widget textScaler property not found on flutter 3.13.9 

### ISSUE THREAD

**Issue by fangsj** [nylo-core/support#26]
Text Widget textScaler property not found on flutter 3.13.9 ,Using textScaleFactor as an alternative

**Comment by agordn52** [comment]
Hi @fangsj,

You'll need to upgrade your Flutter version and upgrade the Nylo frameworkhttps://pub.dev/packages/nylo_framework
I think this is related https://github.com/nylo-core/nylo/issues/87

Hope that helps.
